# This is a basic workflow to help you get started with Actions

name: Build the Twine game

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    tags:
      - 'v*.*.*'

defaults:
  run:
    shell: bash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Check out Electron app template
      uses: actions/checkout@v2
      with:
        repository: lazerwalker/electron-wrapper-template
        path: app

    - name: Set up Electron app environment
      working-directory: ./app
      run: npm install

    - name: move webapp into Electron folder
      run: |
        mv ./src/* ./app/src
        mv ./icon.png ./app

    - name: Put the current git tag into ENV variables
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

    - name: Generate icons
      working-directory: ./app
      run: npm run build-icons

    - name: Build the app
      working-directory: ./app
      env:
          NAME: My Twine game
      run: npm run make

    - name: Release on GitHub
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          app/out/**/*.deb
          app/out/**/*.dmg
          app/out/**/*Setup.exe
          app/out/**/*.rpm
          app/out/**/*.zip